### ISSUE TITLE
Elasticsearch에서 인덱스의 샤드를 노드마다 균등 분배하기 

### ISSUE THREAD

**Issue by occidere** [occidere/notepad#11]
# 인덱스의 샤드를 노드마다 균등 분배하기
## 환경
* 총 5개의 노드가 존재
* 인덱스는 10개의 샤드로 구성
* `shard rebalance settings` 는 기본값
    ````yml
    cluster.routing.allocation.balance.shard: 0.45
    cluster.routing.allocation.balance.index: 0.55
    cluster.routing.allocation.balance.threshold: 1.0
    ````
    ![image](https://user-images.githubusercontent.com/20942871/49198170-42da8180-f3d5-11e8-85a0-87633158fd53.png)

## 상황
* 인덱스의 **샤드들을 각 노드마다 균등하게 분배**하고 싶음
    * 본 예시에선 10개의 샤드를 노드마다 2개씩 배치하고 싶음
* 그러나 대부분의 경우 의도대로 되지 않고, 특정 노드에 쏠리는 현상 발생

## 해결
* `shard rebalance settings` 의 가중치를 아래와 같이 변경
    ````yml
    # 가중치: 노드마다 샤드 개수 밸런싱 < 인덱스마다 샤드 개수 밸런싱
    cluster.routing.allocation.balance.shard: 0
    cluster.routing.allocation.balance.index: 1
    cluster.routing.allocation.balance.threshold: 1.0
    ````
* 쿼리
    ````json
	PUT _cluster/settings
	{
	  "transient": {
	    "cluster.routing.allocation.balance.shard": 0.0,
	    "cluster.routing.allocation.balance.index": 1.0
	  }
	}
    ````
    ![image](https://user-images.githubusercontent.com/20942871/49198585-28a1a300-f3d7-11e8-92ee-a09a52e8865e.png)

## 주의
* 샤드 개수가 노드마다 균등하게 분배되기 적합한 상황인 경우에만 적용할 것
    * 예를들어 노드가 5개인데, 인덱스 세팅이 샤드 4개, 레플리카 1개와 같은 경우엔 제대로 밸런싱이 안될 수 있음
    ![image](https://user-images.githubusercontent.com/20942871/49198822-68b55580-f3d8-11e8-828a-fed7e3ee32bb.png)
* 이미 클러스터에 인덱스가 많은 상황에서 갑자기 설정값을 바꿔버리면, 전부 다 한번에 리밸런싱이 일어날 수 있기 때문에, 작업 전 allocation 설정을 조정한 뒤 제어범위 내에서 수행해야 함
* 일부 샤드들이 이동이 안되며, 아래와 같은 에러가 발생하면 여기 참고
    ````
    there are too many copies of the shard allocated to nodes with attribute [rack],
    there are [2] total configured shard copies for this shard id and [2] total attribute values,
    expected the allocated shard count per attribute [2] to be less than or equal to the
    upper bound of the required number of shards per attribute [1])
    ````

## 참고
* [shard_balancing_heuristics](https://www.elastic.co/guide/en/elasticsearch/reference/current/shards-allocation.html#_shard_balancing_heuristics)
