### ISSUE TITLE
Elasticsearch 의 queue size 변경

### ISSUE THREAD

**Issue by occidere** [occidere/notepad#56]
# Elasticsearch 의 queue size 변경

## 상황
* write.queue_size 등의 큐 사이즈는 기본으로 200인데, 데이터 인입 속도가 큐 처리 속도보다 빨라 계속 쌓이다가, 200을 초과하여 에러 발생

## 해결
* queue_size 값을 증가.
단, queue_size 가 커진다고 해서 병렬성이 증가하는 것은 아니고, 단순히 쌓아놓는 양만 증가하는 것이기 때문에 근본적으로 처리속도를 늘리지 않는 이상 메모리만 증가하는 부작용이 발생할 수도 있음

#### elasticsearch.yml
````yml
threadpool.search.queue_size: 1000
threadpool.index.queue_size: 1000
threadpool.write.queue_size: 1000
````

## 참고
* [Increasing the size of the queue in Elasticsearch?](https://stackoverflow.com/questions/33110310/increasing-the-size-of-the-queue-in-elasticsearch)
* [What happens when a bulk indexing request is sent to Elasticsearch?](https://www.elastic.co/blog/why-am-i-seeing-bulk-rejections-in-my-elasticsearch-cluster)
