### ISSUE TITLE
포드 (Pods)

### ISSUE THREAD

**Issue by occidere** [occidere/notepad#86]
# 포드 (Pods)

* 컨테이너화 된 application 개발 시 여러 application 을 단일 버신에서 스케쥴링되는 하나의 원자 단위로 배치하는 경우가 다수
* 자원 격리는 컨테이서 설계의 목표
* k8s 는 여러 컨테이너를 Pod 라 부르는 하나의 원자 단위로 묶음

<br>

## k8s 의 pods
* pods 는 동일한 실행 환경에서 실행되는 application container 와 volumn 으로 구성된 집합
* k8s 클러스터에서 배포 가능한 최소 artifact
    * pods 에 있는 모든 container 는 동일한 머신에 존재
* pods 의 각 컨테이너는 각자의 cgroup 을 운영하나, 몇가지 linux namespace 를 공유
* 동일한 포드에서 동작하는  application 은 동일한 IP 주소, port(network namespace) 를 공유, 동일한 hostname(UTS namespace)을 갖음
* System V IPC, POSIX 메시지 큐(IPC namespace) 등을 통해 기본 프로세스 간 통신 채널 사용해 상호 통신도 가능

<br>

### Pod 에 무엇을 담아야 하나?
* 각 컨테이너가 서로 다른 머신에 있어도 잘 동작할지를 고민
    * Yes -> 여러 포드를 사용
    * No -> 동일 포드를 사용

<br>

## Pod manifest
* pod manifest 는 k8s API 객체를 선언형 설정 방식으로 텍스트 파일에 표현한 것
* 키 필드와 속성의 쌍으로 구성
* 구조
    * metadata: 포드를 설명
    * spec 의 volumn: volumn을 설명
    * spec 의 containers: 동작할 컨테이너 목록

<br>

* 포드 실행
```bash
kubectl run kuard --image=gcr.io/kuard-sample/kuard-amd64:1
# 파일에서 생성
kubectl apply -f kuard-pod.yaml
```
* 포드 세부사항
```bash
kubectl describe pods kuard
```
* 포드 삭제
```bash
# pod 이름으로 삭제
kubectl delete pods/kuard
# pod 생성 파일로 삭제
kubectl delete -f kuard-pod.yaml
```
    * 종료 시 pod 는 기본적으로 30초의 유예를 갖음
    * pod 삭제 시 관련 컨테이너 데이터도 함께 삭제됨
    보존하려면 `PersistentVolumn` 사용 필요

<br>

### 포트 포워딩
```bash
kubectl port-forward kuard 8080:8080
```

<br>

### 로그 확인
```bash
# 실행중인 인스턴스에서 로그 다운로드해 출력
kubectl logs kuard

# 로그를 스트림 출력
kubectl logs -f kuard
```

<br>

### exec 로 컨테이너에서 명령 실행
```bash
# date 커맨드 실행
kubectl exec kuard date

# bash 쉘 수행
kubectl exec -it kuard -- /bin/bash
```

<br>

### 파일 복사
```bash
# remote container -> local
kubectl cp ${POD_NAME}:/dir/file.txt file.txt

# local -> remote container
kubectl cp file.txt ${POD_NAME}/file.txt
```

<br>

### Liveness probe
* 프로세스 시작, 실행 등 정상적인 동작을 확인해 deadlock 등이 안 걸리고 정상적으로 구동중인지 체크하는 것
* 어플리케이션 별로 특화되므로 pod manifest 에 컨테이너별로 정의해야 함
```yaml
apiVersion; v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
  - image: gcr.io/kuard-sample/kuard-amd64:1
    name: kuard
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      perioadSeconds: 10
      failureThreshold: 3
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
```
